### ISSUE TITLE
Voting skips zero

### ISSUE THREAD

**Issue by phipsgabler** [theShmoo/trompete#1]
Reproduce:

- Make a new post (0 votes)
- Upvote (1 vote)
- Downvote (-1 votes)

**Comment by theShmoo** [comment]
Das war Absicht... Können wir natürlich noch entfernen und man kommt wieder zurück zur 0.

**Comment by phipsgabler** [comment]
Aber wenn einer upvoted und einer downvoted sind das ja nicht -1 Votes?  Wenn, dann müsste man beides anzeigen, wie [hier](https://stackoverflow.com/help/privileges/established-user).  Das würde ich sogar grundsätzlich besser finden, eigentlich.

**Comment by theShmoo** [comment]
Dadurch dass es momentan nur einen user gibt nimmt der User seinen upvote weg und wandelt ihn in einen downvote um.
Das ist so wie in reddit.
Würde der Post bereits einen Vote haben und ich füge einen hinzu hat er dann zwei. Entscheide ich mich um und vote ihn down hat er 0 Punkte.

**Comment by phipsgabler** [comment]
Ah, OK, das ist was anderes natürlich anders... mir war nicht klar, dass alle ein User sind; ich hab gedacht man kriegt einen neuen bei jedem reload.

Mit dem neuen Interface ist das schon viel besser, da ist einem nämlich klar, ob man selbst schon gevotet hat.
